project:
  type: website

website:
  title: "Aarushi Nema"
  description: "A hub for showcasing my portfolio, AI and tech blogs, creative drawings, and podcast episodes that blend innovation with artistry."
  navbar:
    background: "#000000"
    search: true
    pinned: true
    right:
      - about.qmd
      - text: "Blog"
        href: index.qmd
      - icon: github
        href: https://github.com/aarushi-nema
      - icon: linkedin
        href: https://www.linkedin.com/in/aarushi-nema-64a006185/
  page-footer: 
    background: "#000000"
    left: "A hub for showcasing my portfolio, AI and tech blogs, creative drawings, and podcast episodes. All opinions are my own." 
    right: 
      - "© 2025 Aarushi Nema"
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/
format:
  html:
    theme: journal
    css: styles.css
    page-layout: article
    grid:
      margin-width: 450px
      body-width: 600px
    
